apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: node-app1
  ports:
    - protocol: TCP
      port: 80    # Expose port 80 within the cluster
      targetPort: 3000  
  type: ClusterIP
