apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: ibrahimmintal/nginx-reverse-proxy
          ports:
            - containerPort: 443
          volumeMounts:
            - name: nginx-certs
              mountPath: /etc/nginx/certs/localhost.crt
              subPath: tls.crt
              readOnly: true
            - name: nginx-certs
              mountPath: /etc/nginx/certs/localhost.key
              subPath: tls.key
              readOnly: true
            - name: nginx-htpasswd
              mountPath: /etc/nginx/conf.d/.htpasswd
              subPath: .htpasswd
              readOnly: true
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
      volumes:
        - name: nginx-certs
          secret:
            secretName: nginx-certs
        - name: nginx-htpasswd
          secret:
            secretName: nginx-htpasswd
        - name: nginx-config
          configMap:
            name: nginx-config
